- EDA on trafiklsb resrobot API

In [46]:
from dotenv import load_dotenv
import os
import requests

load_dotenv()

API_KEY = os.getenv("API_KEY")

url = f"https://api.resrobot.se/v2.1/trip?format=json&originId=740000002&destId=740000003&passlist=true&showPassingPoints=true&accessId={API_KEY}"

response = requests.get(url)

response.text

result = response.json()
result.keys()

dict_keys(['Trip', 'ResultStatus', 'TechnicalMessages', 'serverVersion', 'dialectVersion', 'planRtTs', 'requestId', 'scrB', 'scrF'])

In [47]:
len(result["Trip"])

5

In [48]:
result["ResultStatus"], result["TechnicalMessages"], result["planRtTs"], result["scrB"]

({'timeDiffCritical': False},
 {'TechnicalMessage': [{'value': '2025-01-07 11:38:03', 'key': 'requestTime'},
   {'value': 'ttp=16417#16603 plancode0=zzlri planid=1736224604 planid0=1736224604 planid_adr=1479298166 plancode_adr=q0r10 srvv=5.45.SAMTRAFIKEN.15.0.1 (customer/hcusamtrafiken/release/2023.10.0) [2023-10-19] tlibv=TRFVER: rel/pproxy/4.00.0 2022-10-24 18:24:51 +0200 Relay_EnrichmentProxy v1 jno=1',
    'key': 'backendInfo'}]},
 '1970-01-01T01:00:00.000+01:00',
 '3|OB|MTµ14µ42460µ42460µ42648µ42648µ0µ0µ365µ42458µ1µ0µ1122µ0µ0µ-2147483648µ1µ2|PDHµ378355956619a5b7de5fd8151f63f427|RDµ7012025|RTµ113803|USµ1|RSµINIT')

In [49]:
# checks first trip keys
example_trip = result["Trip"][0]
example_trip.keys()

dict_keys(['Origin', 'Destination', 'ServiceDays', 'LegList', 'calculation', 'TripStatus', 'idx', 'tripId', 'ctxRecon', 'duration', 'rtDuration', 'checksum'])

In [50]:
example_trip["Origin"]

{'name': 'Göteborg Centralstation',
 'type': 'ST',
 'id': 'A=1@O=Göteborg Centralstation@X=11973479@Y=57708895@U=1@L=740000002@',
 'extId': '740000002',
 'lon': 11.973479,
 'lat': 57.708895,
 'routeIdx': 0,
 'prognosisType': 'PROGNOSED',
 'time': '11:40:00',
 'date': '2025-01-07',
 'minimumChangeDuration': 'PT15M'}

In [51]:
example_trip["Destination"]

{'name': 'Malmö Centralstation',
 'type': 'ST',
 'id': 'A=1@O=Malmö Centralstation@X=13000910@Y=55609456@U=1@L=740000003@',
 'extId': '740000003',
 'lon': 13.00091,
 'lat': 55.609456,
 'routeIdx': 12,
 'prognosisType': 'PROGNOSED',
 'time': '14:48:00',
 'date': '2025-01-07',
 'minimumChangeDuration': 'PT15M'}

In [52]:
example_trip["ServiceDays"]

[{'planningPeriodBegin': '2024-12-11',
  'planningPeriodEnd': '2025-06-15',
  'sDaysR': 'inte varje dag',
  'sDaysI': '7. jan t o m 8. jun 2025; utom 12. t o m 21. apr 2025, 26. apr',
  'sDaysB': 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC00F7FFFFFFFFFF000'}]

In [53]:

example_trip["LegList"].keys()

dict_keys(['Leg'])

In [54]:
len(example_trip["LegList"]["Leg"])

1

In [55]:
example_trip["LegList"]["Leg"][0].keys()

dict_keys(['Origin', 'Destination', 'Notes', 'JourneyDetailRef', 'JourneyStatus', 'Product', 'Stops', 'JourneyDetail', 'id', 'idx', 'name', 'number', 'category', 'type', 'reachable', 'waitingState', 'direction', 'directionFlag', 'duration'])

In [56]:
stops = example_trip["LegList"]["Leg"][0]["Stops"]["Stop"]
stops

[{'name': 'Göteborg Centralstation',
  'id': 'A=1@O=Göteborg Centralstation@X=11973479@Y=57708895@U=1@L=740000002@',
  'extId': '740000002',
  'routeIdx': 0,
  'lon': 11.973479,
  'lat': 57.708895,
  'depPrognosisType': 'PROGNOSED',
  'depTime': '11:40:00',
  'depDate': '2025-01-07',
  'depDir': 'Köpenhamn Österport (Danmark)',
  'minimumChangeDuration': 'PT15M'},
 {'name': 'Mölndal station',
  'id': 'A=1@O=Mölndal station@X=12018722@Y=57655958@U=1@L=740000315@',
  'extId': '740000315',
  'routeIdx': 1,
  'lon': 12.018722,
  'lat': 57.655958,
  'depTime': '11:48:00',
  'depDate': '2025-01-07',
  'arrTime': '11:48:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT9M'},
 {'name': 'Kungsbacka station',
  'id': 'A=1@O=Kungsbacka station@X=12079614@Y=57490556@U=1@L=740000161@',
  'extId': '740000161',
  'routeIdx': 2,
  'lon': 12.079614,
  'lat': 57.490556,
  'depTime': '11:59:00',
  'depDate': '2025-01-07',
  'arrTime': '11:59:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT5M'},
 {'name': 'Varberg station',
  'id': 'A=1@O=Varberg station@X=12248081@Y=57109378@U=1@L=740000110@',
  'extId': '740000110',
  'routeIdx': 3,
  'lon': 12.248081,
  'lat': 57.109378,
  'depTime': '12:29:00',
  'depDate': '2025-01-07',
  'arrTime': '12:25:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT5M'},
 {'name': 'Falkenberg station',
  'id': 'A=1@O=Falkenberg station@X=12507555@Y=56919768@U=1@L=740001579@',
  'extId': '740001579',
  'routeIdx': 4,
  'lon': 12.507555,
  'lat': 56.919768,
  'depTime': '12:45:00',
  'depDate': '2025-01-07',
  'arrTime': '12:45:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT4M'},
 {'name': 'Halmstad Centralstation',
  'id': 'A=1@O=Halmstad Centralstation@X=12864840@Y=56669275@U=1@L=740000080@',
  'extId': '740000080',
  'routeIdx': 5,
  'lon': 12.86484,
  'lat': 56.669275,
  'depTime': '13:13:00',
  'depDate': '2025-01-07',
  'arrTime': '13:03:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT10M'},
 {'name': 'Laholm station',
  'id': 'A=1@O=Laholm station@X=12999606@Y=56501905@U=1@L=740000058@',
  'extId': '740000058',
  'routeIdx': 6,
  'lon': 12.999606,
  'lat': 56.501905,
  'depTime': '13:25:00',
  'depDate': '2025-01-07',
  'arrTime': '13:25:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT9M'},
 {'name': 'Båstad station',
  'id': 'A=1@O=Båstad station@X=12906991@Y=56431834@U=1@L=740001603@',
  'extId': '740001603',
  'routeIdx': 7,
  'lon': 12.906991,
  'lat': 56.431834,
  'depTime': '13:32:00',
  'depDate': '2025-01-07',
  'arrTime': '13:32:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT4M'},
 {'name': 'Ängelholm station',
  'id': 'A=1@O=Ängelholm station@X=12854197@Y=56245200@U=1@L=740000064@',
  'extId': '740000064',
  'routeIdx': 8,
  'lon': 12.854197,
  'lat': 56.2452,
  'depTime': '13:43:00',
  'depDate': '2025-01-07',
  'arrTime': '13:43:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT10M'},
 {'name': 'Helsingborg Centralstation',
  'id': 'A=1@O=Helsingborg Centralstation@X=12694261@Y=56044408@U=1@L=740000044@',
  'extId': '740000044',
  'routeIdx': 9,
  'lon': 12.694261,
  'lat': 56.044408,
  'depTime': '14:07:00',
  'depDate': '2025-01-07',
  'arrTime': '14:04:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT9M'},
 {'name': 'Landskrona station',
  'id': 'A=1@O=Landskrona station@X=12857406@Y=55878898@U=1@L=740001554@',
  'extId': '740001554',
  'routeIdx': 10,
  'lon': 12.857406,
  'lat': 55.878898,
  'depTime': '14:19:00',
  'depDate': '2025-01-07',
  'arrTime': '14:19:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT9M'},
 {'name': 'Lund Centralstation',
  'id': 'A=1@O=Lund Centralstation@X=13186897@Y=55708094@U=1@L=740000120@',
  'extId': '740000120',
  'routeIdx': 11,
  'lon': 13.186897,
  'lat': 55.708094,
  'depTime': '14:38:00',
  'depDate': '2025-01-07',
  'arrTime': '14:36:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT10M'},
 {'name': 'Malmö Centralstation',
  'id': 'A=1@O=Malmö Centralstation@X=13000910@Y=55609456@U=1@L=740000003@',
  'extId': '740000003',
  'routeIdx': 12,
  'lon': 13.00091,
  'lat': 55.609456,
  'arrTime': '14:48:00',
  'arrDate': '2025-01-07',
  'minimumChangeDuration': 'PT15M'}]

In [57]:
for stop in stops: 
    print(f"{stop['name']}") (stop.get["arvTime"])

Göteborg Centralstation

TypeError: 'builtin_function_or_method' object is not subscriptable

- Stop lookup

In [58]:
location = "göteborg"
url = f"https://api.resrobot.se/v2.1/location.name?input={location}&format=json&accessId={API_KEY}"
response = requests.get(url)
result = response.json()
result.keys()

dict_keys(['stopLocationOrCoordLocation', 'TechnicalMessages', 'serverVersion', 'dialectVersion', 'requestId'])

In [59]:
stop_locations = result["stopLocationOrCoordLocation"]
len(stop_locations)

10

In [60]:
stop_locations[0]

{'StopLocation': {'productAtStop': [{'icon': {'res': 'prod_gen'}, 'cls': '2'},
   {'icon': {'res': 'prod_gen'}, 'cls': '4'},
   {'icon': {'res': 'prod_gen'}, 'cls': '8'},
   {'icon': {'res': 'prod_gen'}, 'cls': '16'},
   {'icon': {'res': 'prod_gen'}, 'cls': '64'},
   {'icon': {'res': 'prod_gen'}, 'cls': '128'},
   {'icon': {'res': 'prod_gen'}, 'cls': '256'}],
  'timezoneOffset': 60,
  'id': 'A=1@O=GÖTEBORG@X=11973479@Y=57708895@U=1@L=740098001@B=1@p=1736224604@',
  'extId': '740098001',
  'name': 'GÖTEBORG',
  'lon': 11.973479,
  'lat': 57.708895,
  'weight': 15424,
  'products': 222,
  'meta': True,
  'minimumChangeDuration': 'PT26M'}}

In [61]:
stop_locations[0]["StopLocation"].keys()

dict_keys(['productAtStop', 'timezoneOffset', 'id', 'extId', 'name', 'lon', 'lat', 'weight', 'products', 'meta', 'minimumChangeDuration'])

In [62]:
stop_locations[0]["StopLocation"]["name"]

'GÖTEBORG'

In [63]:
# :<50  -> left align in a 50-character wide field
print(f"{'Stop':<50} {'extId'}")
for stop_location in stop_locations:
    stop = stop_location["StopLocation"]
    print(f"{stop.get('name'):<50} {stop.get('extId')}")

Stop                                               extId
GÖTEBORG                                           740098001
Göteborg Centralstation                            740000002
Göteborg Sävenäs lokstation                        740016365
GÖTEBORG GAMLESTADEN                               740098526
Göteborg Korsvägen                                 740015578
Göteborg Kungsportsplatsen                         740016358
Göteborg Stenpiren                                 740072430
Göteborg Eketrägatan                               740025624
Göteborg Vårväderstorget                           740025707
Göteborg Axel Dahlströms torg                      740025608

In [64]:
def access_id_from_location(location):
    url = f"https://api.resrobot.se/v2.1/location.name?input={location}&format=json&accessId={API_KEY}"

    try:
        response = requests.get(url)
        result = response.json()

        print(f"{'Name':<50} extId")

        for stop in result.get("stopLocationOrCoordLocation"):
            stop_data = next(iter(stop.values()))

            # returns None if extId doesn't exist
            if stop_data.get("extId"):
                print(f"{stop_data['name']:<50} {stop_data['extId']}")

    except requests.exceptions.RequestException as err:
        print(f"Network or HTTP error: {err}")

access_id_from_location("malm")

Name                                               extId
Malm (Gullspång kn)                                740062061
Malmö Centralstation                               740000003
Malmö Triangeln station                            740001587
Malmö Hyllie station                               740001586
Malmö Svågertorp station                           740001546
Malmö Persborg station                             740001486
MALMÖ                                              740098548
Malmö Rosengård station                            740001621
Malmö Östervärn station                            740001483
Malmö Fosieby station                              740001553

In [65]:
# korsvägen
stop_id=740015578
url = f"https://api.resrobot.se/v2.1/departureBoard?id={stop_id}&format=json&accessId={API_KEY}"

response = requests.get(url)
results = response.json()
results.keys()

dict_keys(['Departure', 'TechnicalMessages', 'serverVersion', 'dialectVersion', 'planRtTs', 'requestId'])

In [66]:
import pandas as pd 

df_timetable = pd.DataFrame(results["Departure"])
df_timetable.head()

,JourneyDetailRef,JourneyStatus,ProductAtStop,Product,Notes,name,type,stop,stopid,stopExtId,lon,lat,time,date,reachable,direction,directionFlag
0,{'ref': '1|30358|16|1|7012025'},P,"{'icon': {'res': 'prod_gen'}, 'operatorInfo': ...","[{'icon': {'res': 'prod_gen'}, 'operatorInfo':...","{'Note': [{'value': 'Lag 2015:953 tillämpas', ...",Länstrafik - Spårväg 4,ST,Göteborg Korsvägen,A=1@O=Göteborg Korsvägen@X=11986918@Y=57696742...,740015578,11.986918,57.696742,11:44:00,2025-01-07,True,Mölndals Innerstad,2
1,{'ref': '1|154487|5|1|7012025'},P,"{'icon': {'res': 'prod_gen'}, 'operatorInfo': ...","[{'icon': {'res': 'prod_gen'}, 'operatorInfo':...","{'Note': [{'value': 'Lag 2015:953 tillämpas', ...",Länstrafik - Buss RÖD,ST,Göteborg Korsvägen,A=1@O=Göteborg Korsvägen@X=11986918@Y=57696742...,740015578,11.986918,57.696742,11:44:00,2025-01-07,True,Önneröd (Härryda kn),2
2,{'ref': '1|159648|4|1|7012025'},P,"{'icon': {'res': 'prod_gen'}, 'operatorInfo': ...","[{'icon': {'res': 'prod_gen'}, 'operatorInfo':...","{'Note': [{'value': 'Lag 2015:953 tillämpas', ...",Länstrafik - Spårväg 6,ST,Göteborg Korsvägen,A=1@O=Göteborg Korsvägen@X=11986918@Y=57696742...,740015578,11.986918,57.696742,11:44:00,2025-01-07,True,Göteborg Varmfrontsgatan,2
3,{'ref': '1|64281|8|1|7012025'},P,"{'icon': {'res': 'prod_gen'}, 'operatorInfo': ...","[{'icon': {'res': 'prod_gen'}, 'operatorInfo':...","{'Note': [{'value': 'Lag 2015:953 tillämpas', ...",Länstrafik - Spårväg 8,ST,Göteborg Korsvägen,A=1@O=Göteborg Korsvägen@X=11986918@Y=57696742...,740015578,11.986918,57.696742,11:45:00,2025-01-07,True,Angered centrum (Göteborg kn),1
4,{'ref': '1|116850|5|1|7012025'},P,"{'icon': {'res': 'prod_gen'}, 'operatorInfo': ...","[{'icon': {'res': 'prod_gen'}, 'operatorInfo':...","{'Note': [{'value': 'Lag 2015:953 tillämpas', ...",Länstrafik - Buss 18,ST,Göteborg Korsvägen,A=1@O=Göteborg Korsvägen@X=11986918@Y=57696742...,740015578,11.986918,57.696742,11:45:00,2025-01-07,True,Körkarlens gata (Göteborg kn),2

In [67]:
df_timetable_cleaned = df_timetable[["name", "stop", "lon", "lat", "direction", "date", "time"]]
df_timetable_cleaned

,name,stop,lon,lat,direction,date,time
0,Länstrafik - Spårväg 4,Göteborg Korsvägen,11.986918,57.696742,Mölndals Innerstad,2025-01-07,11:44:00
1,Länstrafik - Buss RÖD,Göteborg Korsvägen,11.986918,57.696742,Önneröd (Härryda kn),2025-01-07,11:44:00
2,Länstrafik - Spårväg 6,Göteborg Korsvägen,11.986918,57.696742,Göteborg Varmfrontsgatan,2025-01-07,11:44:00
3,Länstrafik - Spårväg 8,Göteborg Korsvägen,11.986918,57.696742,Angered centrum (Göteborg kn),2025-01-07,11:45:00
4,Länstrafik - Buss 18,Göteborg Korsvägen,11.986918,57.696742,Körkarlens gata (Göteborg kn),2025-01-07,11:45:00
...,...,...,...,...,...,...,...
172,Länstrafik - Buss 61,Göteborg Korsvägen,11.986918,57.696742,Masthugget (Göteborg kn),2025-01-07,12:43:00
173,Länstrafik - Spårväg 2,Göteborg Scandinavium,11.985875,57.700445,Göteborg Axel Dahlströms torg,2025-01-07,12:43:00
174,Länstrafik - Spårväg 4,Göteborg Korsvägen,11.986918,57.696742,Mölndals Innerstad,2025-01-07,12:44:00
175,Länstrafik - Buss RÖD,Göteborg Korsvägen,11.986918,57.696742,Önneröd (Härryda kn),2025-01-07,12:44:00
176,Länstrafik - Spårväg 6,Göteborg Korsvägen,11.986918,57.696742,Göteborg Varmfrontsgatan,2025-01-07,12:44:00

In [68]:
df_timetable_cleaned["name"].value_counts()

name
Länstrafik - Spårväg 6    25
Länstrafik - Spårväg 8    24
Länstrafik - Spårväg 2    24
Länstrafik - Buss X4      17
Länstrafik - Buss 18      16
Länstrafik - Spårväg 4    13
Länstrafik - Buss 63      12
Länstrafik - Spårväg 5    12
Länstrafik - Buss 61      12
Länstrafik - Buss RÖD      9
Länstrafik - Buss 758      4
Länstrafik - Buss 100      3
Länstrafik - Buss 101      2
Flygtransfer - Buss .      2
Länstrafik - Buss 300      2
Name: count, dtype: int64